# Generated by Django 3.1.5 on 2021-02-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('tecnologias', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('imagen', models.ImageField(default='null', upload_to='Proyectos')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
