# Generated by Django 3.1.5 on 2021-05-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_proyecto_urlimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='urlimg',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
